// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOR1t1WtvXAfh4KfN9hC8WikD-O-ftYBg',
    appId: '1:965719182148:web:2081c6177f2928fc97a511',
    messagingSenderId: '965719182148',
    projectId: 'nemsu-clearance',
    authDomain: 'nemsu-clearance.firebaseapp.com',
    databaseURL: 'https://nemsu-clearance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemsu-clearance.appspot.com',
    measurementId: 'G-MQWHQ8RP7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB44jCbLe7vn5vd3-JB23u2agBtuGskpRQ',
    appId: '1:965719182148:android:cd0cdc77139d8a0c97a511',
    messagingSenderId: '965719182148',
    projectId: 'nemsu-clearance',
    databaseURL: 'https://nemsu-clearance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemsu-clearance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCR7QNYUQi-vdvMQuWG6uSTVQcy59fTg',
    appId: '1:965719182148:ios:4a029a0a683c4a8197a511',
    messagingSenderId: '965719182148',
    projectId: 'nemsu-clearance',
    databaseURL: 'https://nemsu-clearance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemsu-clearance.appspot.com',
    iosBundleId: 'com.example.nemsuClearance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCR7QNYUQi-vdvMQuWG6uSTVQcy59fTg',
    appId: '1:965719182148:ios:4a029a0a683c4a8197a511',
    messagingSenderId: '965719182148',
    projectId: 'nemsu-clearance',
    databaseURL: 'https://nemsu-clearance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemsu-clearance.appspot.com',
    iosBundleId: 'com.example.nemsuClearance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOR1t1WtvXAfh4KfN9hC8WikD-O-ftYBg',
    appId: '1:965719182148:web:5e4ac8d1f52c527097a511',
    messagingSenderId: '965719182148',
    projectId: 'nemsu-clearance',
    authDomain: 'nemsu-clearance.firebaseapp.com',
    databaseURL: 'https://nemsu-clearance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nemsu-clearance.appspot.com',
    measurementId: 'G-0WZ72JNTLX',
  );
}
